services:

  carla-client:
    image: ghcr.io/openads-project/carla-simulator:client_v0.10.0-1.1.1
    environment:
      CARLA_HOST: carla-server
      CARLA_PORT: 2000
    command:
      - sleep
      - infinity
